dryrun = false
scanner = "metadata"
failon = "high"
metadata_client = "containeranalysis"

binauth_project = "your-project-here"
signer = "kms"
valid_repos = [
    "gcr.io/path/to/my/project",
]

trusted_builder_identities = [
    "email@example.com",
    "idcloudbuild.gserviceaccount.com"
]

trusted_projects = [
    "trusted-builds"
]

[checks]
diy      = true
nobody   = true
provenance = true
snakeoil = true

[server]
port = 8000
require_auth = true
username = "username here"
password = "bcrypt hash of your password"

[ejson]
dir = "/key"
secrets = "/etc/voucher/secrets.production.ejson"

[metrics]
backend = "statsd"
# OR: backend = "datadog"
# OR: backend = "opentelemetry"
tags = []

# for statsd metrics backend
[statsd]
addr = "localhost:8125"
sample_rate = 0.1

# for opentelemetry backend
[opentelemetry]
addr = "grpc://localhost:4317"
insecure = true

[repository.shopify]
org-url = "https://github.com/Shopify"

[repository.grafeas]
org-url = "https://github.com/grafeas"

[[kms_keys]]
check = "diy"
path = "projects/<GCP project>/locations/global/keyRings/<key ring>-keys/cryptoKeys/<key name>/cryptoKeyVersions/<key version>"
algo = "SHA512"

[[kms_keys]]
check = "snakeoil"
path = "projects/<GCP project>/locations/global/keyRings/<key ring>-keys/cryptoKeys/<key name>/cryptoKeyVersions/<key version>"
algo = "SHA512"

[grafeasos]
hostname = ""
version = ""
vuln_project = ""
