dryrun = false
scanner = "metadata"
failon = "high"
metadata_client = "containeranalysis"

binauth_project = "your-project-here"
signer = "kms"
valid_repos = [
    "gcr.io/path/to/my/project",
]

trusted_builder_identities = [
    "email@example.com",
    "idcloudbuild.gserviceaccount.com"
]

trusted_projects = [
    "trusted-builds"
]

[checks]
diy      = true
nobody   = true
provenance = true
snakeoil = true

[server]
port = 8000
require_auth = true
username = "username here"
password = "bcrypt hash of your password"

[ejson]
dir = "/key"
secrets = "/etc/voucher/secrets.production.ejson"

[metrics]
backend = "statsd"
# OR: backend = "datadog"
# OR: backend = "opentelemetry"
tags = []

# for statsd metrics backend
[statsd]
addr = "localhost:8125"
sample_rate = 0.1

# for opentelemetry backend
[opentelemetry]
addr = "grpc://localhost:4317"
insecure = true

[repository.shopify]
org-url = "https://github.com/Shopify"

[repository.grafeas]
org-url = "https://github.com/grafeas"

[[kms_keys]]
check = "diy"
path = "projects/<GCP project>/locations/global/keyRings/<key ring>-keys/cryptoKeys/<key name>/cryptoKeyVersions/<key version>"
algo = "SHA512"

[[kms_keys]]
check = "snakeoil"
path = "projects/<GCP project>/locations/global/keyRings/<key ring>-keys/cryptoKeys/<key name>/cryptoKeyVersions/<key version>"
algo = "SHA512"

[grafeasos]
hostname = ""
version = ""
vuln_project = ""

[sbom_vuln]
failon_severity = "critical"
fail_list = [
    "CVE-2022-26945",
    "CVE-2022-29165",
    "CVE-2022-28738",
    "CVE-2021-44228",
    "CVE-2022-25648",
    "CVE-2021-4110",
    "CVE-2021-4188",
    "CVE-2022-0080",
    "CVE-2022-0240",
    "CVE-2022-0326",
    "CVE-2022-0481",
    "CVE-2022-0631",
    "CVE-2022-0632",
    "CVE-2022-0890",
    "CVE-2022-1071",
    "CVE-2022-1106",
    "CVE-2022-1201",
    "CVE-2022-1427",
    "CVE-2021-45105",
    "CVE-2021-45046",
    "CVE-2021-24045",
    "CVE-2021-24037",
    "CVE-2020-1896",
    "CVE-2020-28281",
    "CVE-2021-22555",
    "CVE-2021-43837",
    "CVE-2022-22815",
    "CVE-2022-22816",
    "CVE-2022-22817",
    "CVE-2021-35514",
    "CVE-2021-33564",
    "CVE-2021-33575"
]
